language: java
os:
  - linux
services:
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
script: mvn clean install
after_success:
  - travis_wait 20 mvn clean test jacoco:report coveralls:report -q
cache:
  directories:
    - $HOME/.m2