language: java
jdk:
  - openjdk8
os:
  - linux
script: mvn clean install
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email:
    recipients:
      - jameshareuk@gmail.com
    on_success: change
    on_failure: always